// AUTO-GENERATED by design-inventor
// Win Air Cleaning — Airy California wellness: bright red-blue on off-white with flowing organic animations
// Logo-anchored: yes

export const designConfig = {

  colors: {
    primary:       '#D93B4D',
    primaryLight:  '#FDE8EB',
    primaryDark:   '#8C1F2E',
    secondary:     '#3578CC',
    accent:        '#2CBAB5',
    background:    '#FAFBFD',
    surface:       '#F0F4F7',
    surfaceDark:   '#1A2538',
    textPrimary:   '#1A2538',
    textSecondary: '#5A6B7D',
    textLight:     '#FFFFFF',
    border:        '#D8DEE6',
  },

  fonts: {
    display:           'Urbanist',
    body:              'Source Sans 3',
    googleFontsUrl:    'https://fonts.googleapis.com/css2?family=Urbanist:wght@300;400;600;800&family=Source+Sans+3:wght@400;500;600&display=swap',
    headingWeight:     'font-extrabold',
    headingTracking:   'tracking-tight',
    headingLineHeight: 'leading-tight',
    labelsUppercase:   true,
  },

  hero: {
    pattern:          'Atmosphere Hero',
    backgroundType:   'gradient-mesh',
    contentAlignment: 'center',
    ctaShape:         'rounded-full',
    hasStats:         true,
  },

  services: {
    pattern:                'Breeze Showcase Carousel',
    requiresClientComponent: true,
    cardImageAspect:        'portrait',
    sectionBg:              'bg-surface',
    headerAlignment:        'text-center',
  },

  colorMood: {
    dominantTone: 'light',
  },

  style: {
    name: 'california-breeze',

    headerType:   'floating-glass',
    hasMegaMenu:  false,
    hasTopBar:    false,
    mobileStyle:  'fullscreen-overlay',

    hasScrollProgress:    false,
    hasParallax:          false,
    hasFloatingBlobs:     false,
    hasTiltCards:         false,
    hasMagneticButtons:   true,
    hasSplitText:         true,
    hasPinnedSteps:       false,
    hasCursorFollower:    false,
    hasGsapScrollTrigger: true,
    hasLenisScroll:       true,
    hasParticleHero:      true,
    hasSwiperCarousel:    true,
    hasVanillaTilt:       false,
    hasGsapTextReveal:    true,
    hasScrollScrub:       true,
    hasCursorSpotlight:   false,
    hasRippleClick:       false,

    counterStyle:         'ease-out',

    hasImageMarquee:      false,
    hasProjectGallery:    false,
    hasSlideshowHero:     false,
    hasBeforeAfter:       true,
    hasPolaroidGallery:   false,
    hasHoverReveal:       false,
    hasHorizontalTheater: false,
    textDensity:          'standard',
  },

  sectionOrder: [
    'Hero',
    'StatsBar',
    'Services',
    'WhyUs',
    'Testimonials',
    'ProcessSteps',
    'BeforeAfter',
    'FAQ',
    'Areas',
    'CTA',
  ],

  sections: {
    stats:        { bg: 'bg-surfaceDark', textColor: 'text-white', numberColor: 'text-accent' },
    services:     { bg: 'bg-surface', pattern: 'dot-grid' },
    whyUs:        { bg: 'bg-background', textColor: 'text-textPrimary' },
    testimonials: { style: 'ticker-marquee', bg: 'bg-surfaceDark' },
    processSteps: { bg: 'bg-surface', connector: 'wave-svg' },
    beforeAfter:  { bg: 'bg-background', layout: 'side-by-side' },
    faq:          { bg: 'bg-surfaceDark', style: 'numbered-reveal' },
    areas:        { bg: 'bg-surface', style: 'arrow-link-list' },
    cta:          { bg: 'bg-gradient', gradient: 'linear-gradient(135deg, #8C1F2E 0%, #1A2538 100%)', hasBackgroundImage: false },
  },

} as const;

export type DesignConfig = typeof designConfig;
